### ISSUE TITLE
Tile shadow is mirrored wrong when laid out in a "C" shape

### ISSUE THREAD

**Issue by PoleyMagik** [coppersalts/HTML5b#4]
![image](https://user-images.githubusercontent.com/59105820/181476637-4df05f33-abb3-4211-afe8-dd01dabf51ee.png)

**Comment by coppersalts** [comment]
I always thought this was an OG bug since I didn't really change the code for adding ambient shadows, but I never actually tested it to see if this was true. And as it turns out the flash version doesn't have this problem, so the problem originates somewhere in HTML5b.
<img width="170" alt="Screen Shot 2022-07-28 at 08 14 32" src="https://user-images.githubusercontent.com/54867664/181515599-363f8342-54ae-40d6-a090-a44d037cd52b.png">

I don't know how this happened, but it turns out the asset itself is like that. `s0013.svg` has the top left gradient flipped like that. I'll fix the vector file, regenerate the `images.json` file, and the fix should be out with the next update.
