### ISSUE TITLE
load button not working

### ISSUE THREAD

**Issue by yonka585** [coppersalts/HTML5b#8]
so for some reason, after the first time successfully using the feature, the load button in editor stopped working

https://user-images.githubusercontent.com/110620343/182888753-e3eaf9a2-9480-4388-a855-5e6dfc7ad6a9.mov

i've tried reloading the website a few times and i have waited for, as of writing this, the past 5 minutes, and i've closed out all other apps besides the browser itself

any solutions?

**Comment by coppersalts** [comment]
Level loading should happen almost instantly and you shouldn't have to wait for it. The text box is closed after the level string is parsed, so if it disappears that means that it either loaded successfully or there was an error when loading it. If it were taking a long time to load it would likely be frozen on the text box and not an empty level.

Most errors are caught in the level creator and displayed as a message in front of the level, but here there was no message in the video, it's likely that it was an error that wasn't caught (in which case it will be visible in the console), or it was one of the three errors that are caught, but don't have a message to go with them. Which are:
- If there are only blank lines in the string.
- If there's only one line after the blank lines.
- If there are more or fewer than five comma separated values in the line after the title.

While there are five comma separated values there, it's possible that they could've gotten converted to special commas by a rich text editor which aren't recognized by the level loader. While I can't confirm this since I don't have the string you have, it's the best explanation I could think of. I will add a message to this one in the next update.

**Comment by yonka585** [comment]
would google slides be a rich text editor? in order to save levels I'm building, I paste the string on a google slide, but from what the last paragraph said that could be an issue

**Comment by yonka585** [comment]
also this was the string i got after pasting it in google slides (the other stuff shouldn't really matter, just top):
 
Extensive
64,36,04,11,L
/......Z.............o..........................................
/......Z.............j..........................................
/......Z.............o.................8........................
/......Z.............j.................8........................
/......Z.............o.....6...........8........................
/......Z....i........j.....6.........r98........................
/@@@@@@////////......//////6.........8V8£.......................
/......M....../....../..../6.........888........................
/......N....../....../..../////MN/....8.........................
/......M....../....../.........../....8.........................
/..///./V/..../777777/.........../...<8.........................
/../././//..../??7777/..../.h..../...88.........................
/../././....../777777/....////////....8.........................
/;;/.///....../777777/....////////....8.........................
////......///;/777777/....////////;<<<8.........................
/........./7///777777/....6...........8.........................
/.....///7/7/7/777777/....6...........8.........................
/...../7/7/7/7/7777??/....66....................................
///////7/7/7/7/777777/....66....................................
/=====/7/7/7/7/777777/....66....................................
/=====/7/7/7/7/777777/....66....................................
/=====/7/7/7/7/777777/....66....................................
/=====/7/7/7/7/777777/////////////..............................
/=====/7/7/7/7/???777/77777777777/..............................
///////7/7/7/7/777777777777777777/..............................
/7777777/7/777/777777777777777777/..............................
/7777777/7/777/777777777777777777/..............................
/7777777070777/777777777717777777/..............................
/7777777777777/?7777?////////77@@/..............................
/77777777777777777777/777777777@@/..............................
/77777777777777777777/77777777777/..............................
/77777777777777777777/77777777777/..............................
/7u/77777777777777777/77777777777/..............................
////7777777777/777777/77777777777/..............................
/xx/7777777777/777777/:77?7777777/..............................
/xx/1111111111/777777/////////;;;/..............................
00,23.40,05.88,10
38,13.40,04.68,06
48,18.40,06.78,04 0911111111111111111111111111222222222222201333333333333300000000000000000000000000
46,29.70,07.78,06
01
00H Looks like I'm up for a little basketball....
000000

**Comment by coppersalts** [comment]
The comma conversion thing only happens in some editors like Microsoft word and I can confirm that those commas are the normal commas, so that can be ruled out as the cause. I copied this into HTML5b and it loaded just fine. I tried copying it into Google slides first and it still worked.

It's still possible that it was some uncaught error (in which case you can find what that error was by opening the javascript console) or it was one of the other two caught errors that didn't have a message tied to them. To see which one it is you'll need to check the title of the level and the javascript console for errors.

Level loader should run the same across browsers and operating systems, so if either of them are the case it probably has something to do with my hacked together solution for getting pasting to work across browsers and that's feeding a weird input to the level loader.

**Comment by yonka585** [comment]
huh
it just now worked
i think it sometimes works and sometimes doesn't
well thanks for your help and insight lol

**Comment by yonka585** [comment]
also i just opened console and found this error:
Uncaught TypeError: navigator.clipboard.readText is not a function
that was probably an error from earlier

**Comment by coppersalts** [comment]
oh yeah that error is normal. it happens in all non-chromium browsers.
